version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./database:/docker-entrypoint-initdb.d

    command: mongod

  client:
    build: ./numer
    ports:
      - "1234:3000"
    depends_on:
      - server

  server:
    build: ./backend
    ports:
      - "3005:3005"
    depends_on:
      - mongo

    links:
      - mongo
